language: cpp

env:
  global:
    - IsTravis=1

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

install:
  - sudo apt-get update
  - sudo apt-get install libsdl1.2-dev

script:
  - cd Rogue
  - make
#  - make test

#after_success:
#  - sudo pip install cpp-coveralls
#  - coveralls -b .
